language: c

compiler:
 - gcc
 - clang

script:
 - cmake .
 - make

notifications:
 email:
  recipients:
   - audwns392@naver.com
  on_success: never
  on_failure: always

deploy:
 provider: releases
 api_key: $GITHUB_TOKEN
 skip_cleanup: true
 on:
  tags: true
