language: c

compiler:
	- gcc
	- clang

branches:
	only:
		- master

notifications:
	slack:
	email:
		recipients:
			- audwns392@naver.com
			- 21600343@handong.edu

script: "gcc maker.c"

deploy:

git:
	depth: 4


